### PR TITLE
Issue 24 extendedVariables supported in maven cli

### PR DESCRIPTION
**Pull request by vhochstein**

### CODE REVIEW

**Comment by vhochstein** [comment]
Travis is complaining for java 8: 
java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Do you have an idea why ?

**Comment by tomasbjerre** [comment]
I thin it is:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/pom.xml#L45

Should be:
```
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
```

**Comment by vhochstein** [comment]
ah ok, you are still supporting java 7. I ve used for each loop which was introduced with java 8. 
Do you prefer to increase to java 8 ? or should I use a standard for loop ?

**Comment by tomasbjerre** [comment]
Change it to Java 8 =)

**Comment by vhochstein** [comment]
tried out both options and both fail. :-( travis still complaints about incorrect class version in that fmt plugin

**Comment by tomasbjerre** [comment]
I can take care of it later. You can just leave it like this.

Den fre 15 jan. 2021 11:35Volker Hochstein <notifications@github.com> skrev:

**Pull request merged**
